---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wif-bo-api${HASH_BRANCH_NAME}
  labels:
    app: wif-bo-api${HASH_BRANCH_NAME}
    branch: wif-bo${HASH_BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wif-bo-api${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: wif-bo-api${HASH_BRANCH_NAME}
    spec:
      containers:
        - image: ${DS_AGGREGATOR_REGISTRY}/api:${IMAGE_TAG}
          name: wif-bo-api
          ports:
            - containerPort: ${PORT}
          env:
            - name: API_PORT
              value: "${PORT}"
            - name: API_PREFIX
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: API_PREFIX
            - name: KINTO_URL
              value: "http://kinto${HASH_BRANCH_NAME}:8888"
            - name: KINTO_BUCKET
              value: "wif-bo"
            - name: KINTO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: KINTO_LOGIN
            - name: KINTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: KINTO_PASSWORD
            - name: DS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: DS_TOKEN
            - name: MAIL_USE_TLS
              value: "true"
            - name: MAIL_PORT
              value: "465"
            - name: MAIL_FROM
              value: "wif-bo <contact@wif-bo.beta.gouv.fr>"
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: MAIL_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: MAIL_PASSWORD
            - name: SENTRY_ENABLED
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: SENTRY_ENABLED
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: SENTRY_DSN
            - name: SCHEDULER_CRON_TASK
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: SCHEDULER_CRON_TASK
            - name: SCHEDULER_CRON_DS
              valueFrom:
                secretKeyRef:
                  name: wif-bo-secret
                  key: SCHEDULER_CRON_DS
